name: .NET CI (Windows)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  build-test:
    name: Build & Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/*.sln', '**/*.csproj', '**/global.json', '**/NuGet.config') }}
          restore-keys: |
            nuget-

      - name: Restore
        run: dotnet restore ./

      - name: Build (Release)
        run: dotnet build ./ --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test ./ --configuration Release --no-build `
            --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
          if-no-files-found: ignore

  publish:
    name: Publish App (win-x64)
    needs: build-test
    runs-on: windows-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Fix NETSDK1047 : restore/build with RID
      - name: Restore (win-x64)
        run: dotnet restore ./ -r win-x64

      - name: Build (Release, win-x64)
        run: dotnet build ./ -c Release -r win-x64 --no-restore

      - name: Publish (framework-dependent)
        run: |
          dotnet publish ./ -c Release -r win-x64 --no-restore `
            -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:DebugType=None -p:DebugSymbols=false -p:SelfContained=false `
            -o out/win-x64
          powershell -NoProfile -Command "Compress-Archive -Path out/win-x64/* -DestinationPath out/win-x64.zip"

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-win-x64
          path: out/win-x64.zip

  release:
    name: Create GitHub Release (on tag)
    needs: publish
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-win-x64
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
          generate_release_notes: true
